### ISSUE TITLE
Error running DGL module

### ISSUE THREAD

**Issue by felipeZ** [nlesc-nano/swan#80]
When invoking the DGL module the following error is raised:
```
[16:44:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[16:44:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[16:44:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[16:44:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[16:44:07] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[16:44:07] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[16:44:07] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[16:44:08] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[16:44:08] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[16:44:08] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
Traceback (most recent call last):
  File "./run_model.py", line 91, in <module>
    main()
  File "./run_model.py", line 51, in main
    train_data(prop)
  File "./run_model.py", line 62, in train_data
    data = DGLGraphData(
  File "/home/user/Primer/Python/swan/swan/dataset/dgl_graph_data.py", line 56, in __init__
    super().__init__(
  File "/home/user/Primer/Python/swan/swan/dataset/data_graph_base.py", line 61, in __init__
    self.molecular_graphs = self.compute_graph()
  File "/home/user/Primer/Python/swan/swan/dataset/dgl_graph_data.py", line 71, in compute_graph
    gm = create_molecular_dgl_graph(
  File "/home/user/Primer/Python/swan/swan/dataset/graph/molecular_graph.py", line 92, in create_molecular_dgl_graph
    graph.ndata['x'] = positions                      # [num_atoms, 3]
  File "/home/user/miniconda3/envs/swan/lib/python3.8/site-packages/dgl/view.py", line 81, in __setitem__
    self._graph._set_n_repr(self._ntid, self._nodes, {key : val})
  File "/home/user/miniconda3/envs/swan/lib/python3.8/site-packages/dgl/heterograph.py", line 3992, in _set_n_repr
    raise DGLError('Expect number of features to match number of nodes (len(u)).'
dgl._ffi.base.DGLError: Expect number of features to match number of nodes (len(u)). Got 58 and 57 instead.
```

**Comment by felipeZ** [comment]
The problem is caused by RDKit in combination with DGL. The best solution is to remove the molecules raising the issue.
